spring:
  application:
    name: eureka-server2
server:
  port: 8762
  context-path: /
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone:  http://peer1:8761/eureka/,http://peer3:8763/eureka/