server:
  port: 10002
spring:
  application:
    name: eureka-client-2
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    instance-id: {spring.application.name}:{spring.cloud.client.ipAddress}:{server.port}